[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
solana_time_locked_wallet = "AgrusQgGxVBPiKBjjNAQx82u1KWP1fwAJ1wmkxNVKHWQ"

[programs.devnet]
solana_time_locked_wallet = "AgrusQgGxVBPiKBjjNAQx82u1KWP1fwAJ1wmkxNVKHWQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
